/* tslint:disable */
/* eslint-disable */
/**
 * DevOps Dashboard API
 * API reserved for DevOps Dashboard
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    UserRegisterDtoIn,
    UserRegisterDtoInFromJSON,
    UserRegisterDtoInToJSON,
} from '../models';

export interface RegisterRequest {
    userRegisterDtoIn: UserRegisterDtoIn;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     */
    async registerRaw(requestParameters: RegisterRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.userRegisterDtoIn === null || requestParameters.userRegisterDtoIn === undefined) {
            throw new runtime.RequiredError('userRegisterDtoIn','Required parameter requestParameters.userRegisterDtoIn was null or undefined when calling register.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v1/users/register`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserRegisterDtoInToJSON(requestParameters.userRegisterDtoIn),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async register(requestParameters: RegisterRequest, initOverrides?: RequestInit): Promise<void> {
        await this.registerRaw(requestParameters, initOverrides);
    }

}
