/* tslint:disable */
/* eslint-disable */
/**
 * DevOps Dashboard API
 * API reserved for DevOps Dashboard
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginDtoOut
 */
export interface LoginDtoOut {
    /**
     * 
     * @type {string}
     * @memberof LoginDtoOut
     */
    accessToken: string;
}

export function LoginDtoOutFromJSON(json: any): LoginDtoOut {
    return LoginDtoOutFromJSONTyped(json, false);
}

export function LoginDtoOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginDtoOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'],
    };
}

export function LoginDtoOutToJSON(value?: LoginDtoOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accessToken': value.accessToken,
    };
}

