/* tslint:disable */
/* eslint-disable */
/**
 * DevOps Dashboard API
 * API reserved for DevOps Dashboard
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginDtoIn
 */
export interface LoginDtoIn {
    /**
     * 
     * @type {string}
     * @memberof LoginDtoIn
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof LoginDtoIn
     */
    password: string;
}

export function LoginDtoInFromJSON(json: any): LoginDtoIn {
    return LoginDtoInFromJSONTyped(json, false);
}

export function LoginDtoInFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginDtoIn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
    };
}

export function LoginDtoInToJSON(value?: LoginDtoIn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
    };
}

